name : first workflow
on:
    push:
        branches : master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Run go program
              run : echo Hello zversal